### PR TITLE
feat: emit LESS imports

### PR DESCRIPTION
**Pull request by jiaweihli**
This is used by file watchers.

See https://github.com/dstokes/lessify/pull/7.
Fixes https://github.com/wilson428/node-lessify/issues/18.

### CODE REVIEW

**Comment by jiaweihli** [comment]
Quick ping!  This is a very short PR, I promise :smile:

**Comment by wilson428** [comment]
Thank you! Sort for delay

**Comment by jiaweihli** [comment]
Thanks!  Any chance you can put out an npm release soon?

**Comment by wilson428** [comment]
Done and done. v0.0.11 is on npm

https://www.npmjs.com/package/node-lessify

**Comment by jiaweihli** [comment]
:raised_hands:

**Pull request merged**
