### PR TITLE
update dependencies;

### PR DESCRIPTION
**Pull request by Fazod**
This updates the LESS version so the vulnerabilities are fixed

### CODE REVIEW

**Comment by DXCanas** [comment]
Sorry, hadn't seen this and don't know what's broken Travis. Will merge once I can verify the update locally!

**Comment by Fazod** [comment]
Hey @DXCanas - did you already have time to check this out?

**Comment by DXCanas** [comment]
Wow, thanks for the bump.

I haven't. Making time this week. Sorry about the delay.

**Comment by DXCanas** [comment]
Actually decided to take a quick look right now.

Given that the Travis issue mostly revolves around a "strict mode" violation to a test in the `less` package, I'm leaning towards there being an issue with this newer version of less and the version of node that runs the tests.

Can't spend much more time on this right now, but I'll update if I find anything else.

**Comment by DXCanas** [comment]
@Fazod 

Took me a while, but I've bumped the required version of Node to match the newer version of Less you specced.

Will tag and release new version.

**Comment by DXCanas** [comment]
New version is published, and you've been credited int he readme.

Thanks for the contribution, sorry again about the insane delay.

**Comment by Fazod** [comment]
Thanks so much David - this is great news and no worries, worth the wait :)

**Pull request merged**
